name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          debug: true
          script: |
            # Если папка репозитория ещё не существует, клонируем его
            if [ ! -d "/root/api/.git" ]; then
              git clone https://github.com/karmaKiller3352/vpn-service.git /root/api
            fi

            # Переходим в папку репозитория и обновляем код
            cd /root/api
            git fetch origin
            git reset --hard origin/main

            # Переходим в папку с docker-compose.yml
            cd /root
            # Перезапускаем контейнеры
            docker-compose up --build -d backend
